### ISSUE TITLE
Issues with broadlink rm pro+

### ISSUE THREAD

**Issue by StSei** [hieblmedia/ioBroker.broadlink#12]
Hi! I bought a broadlink rm pro+. It seems that the adapter is not working anymore. After first installation it shows  "green" but not able to scan a frequency (orange LED not on). After restart the adapter is "red" with the folllwing "log code" below. Tried it several times to install/re-install. 

host.raspberrypi | 2017-11-27 20:11:33.455 | error | instance system.adapter.broadlink.0 terminated with code 0 (OK)
-- | -- | -- | --
host.raspberrypi | 2017-11-27 20:11:33.454 | error | Caught by controller[0]:     at UDP.onMessage (dgram.js:548:8)
host.raspberrypi | 2017-11-27 20:11:33.454 | error | Caught by controller[0]:     at Socket.emit (events.js:191:7)
host.raspberrypi | 2017-11-27 20:11:33.454 | error | Caught by controller[0]:     at emitTwo (events.js:106:13)
host.raspberrypi | 2017-11-27 20:11:33.454 | error | Caught by controller[0]:     at Socket. (/opt/iobroker/node_modules/iobroker.broadlink/lib/broadlink.js:309:9)
host.raspberrypi | 2017-11-27 20:11:33.454 | error | Caught by controller[0]:     at Device.emit (events.js:185:7)
host.raspberrypi | 2017-11-27 20:11:33.453 | error | Caught by controller[0]:     at emitNone (events.js:86:13)
host.raspberrypi | 2017-11-27 20:11:33.453 | error | Caught by controller[0]:     at Device. (/opt/iobroker/node_modules/iobroker.broadlink/lib/broadlink.js:254:10)
host.raspberrypi | 2017-11-27 20:11:33.453 | error | Caught by controller[0]:     at emit (events.js:188:7)
host.raspberrypi | 2017-11-27 20:11:33.453 | error | Caught by controller[0]:     at emitOne (events.js:96:13)
host.raspberrypi | 2017-11-27 20:11:33.452 | error | Caught by controller[0]:     at . (/opt/iobroker/node_modules/iobroker.broadlink/main.js:145:12)
host.raspberrypi | 2017-11-27 20:11:33.452 | error | Caught by controller[0]: TypeError: device.checkTemperature is not a function

**Comment by diasDominik** [comment]
Same Problem with my broadlink rm pro +

**Comment by mic1970** [comment]
Same Problem with my broadlink rm pro +
